export const categories = ['İmza & karakter', 'Meyveli & tropik', 'Fresh & ekşi', 'Sert & klasik', 'Kahveli & gece'] as const;
export type Cocktail={id:string;name:string;category:string;eyebrow:string;headline:string;story:string;detail:string;ingredients:string;tags:string[];image:string;bg:string;ink:string;profile:[number,number,number,number];visible:boolean;hero:boolean};
export const initialMenu:Cocktail[]=[
{id:'orange-silk',name:'Orange Silk',category:categories[0],eyebrow:'GÜNÜN İMZASI',headline:'Güneşin|en ipeksi hali.',story:'Portakalın canlı ruhu, bademin yumuşak dokunuşu. İlk yudumdan son ana uzanan zarif bir denge.',detail:'Bazı tatlar kendini anlatmaz, hissettirir. Orange Silk, turunçgillerin aydınlık dünyasını ipeksi bir dokuyla buluşturuyor. İlk anda taze portakal, ardından bademin kremamsı dokunuşu; finalde ise zarif bir narenciye izi. Yumuşak içimin ardında, tekilanın kendinden emin karakteri var.',ingredients:'Tekila · Portakal likörü · Taze portakal · Badem sütü · Lime · Agave',tags:['Narenciyeli','Kremamsı','Dengeli'],image:'/images/orange-silk.webp',bg:'#f7f4ed',ink:'#8e151c',profile:[4,2,4,3],visible:true,hero:true},
{id:'bodrum-cayi',name:'Bodrum Çayı',category:categories[0],eyebrow:'TANIDIK BİR BARDAK, YENİ BİR HİKÂYE',headline:'Bir çay molası.|Bambaşka bir ruh.',story:'İnce belli bir bardakta Ege esintisi. Siyah çayın derinliği, narenciyenin ferahlığıyla buluşuyor.',detail:'İlk bakışta tanıdık. İlk yudumda sürpriz. Siyah çayın karakteri ve beyaz romun hafif dokunuşu, ince belli bardağa yeni bir hikâye taşıyor. Portakal ve limonla açılan lezzet, çayın uzun bitişiyle sakinleşiyor.',ingredients:'Siyah çay infüze beyaz rom · Portakal likörü · Limon · Soğuk demlenmiş siyah çay',tags:['Çay esintili','Aromatik','Narenciyeli'],image:'/images/bodrum-cayi.webp',bg:'#e8edf1',ink:'#263b5e',profile:[2,3,5,3],visible:true,hero:true},
{id:'peachy-10',name:'Peachy 10',category:categories[1],eyebrow:'TROPİK BİR KAÇAMAK',headline:'Yazın keyfi.|On üzerinden on.',story:'Şeftalinin yumuşak, meyveli dünyası. Beyaz romla uzayan, güneşli bir mola.',detail:'Küçük bir küvet, kocaman bir yaz hissi. Şeftalinin sulu tatlılığı beyaz romla buluşuyor; yumuşak içimi ve beklenmedik sunumuyla sohbetin en neşeli yerine yerleşiyor.',ingredients:'Beyaz rom · Şeftali',tags:['Şeftalili','Tropik','Yumuşak'],image:'/images/peachy-10.webp',bg:'#f7dfd6',ink:'#a32b28',profile:[4,2,3,2],visible:true,hero:true},
{id:'passion-10',name:'Passion 10',category:categories[1],eyebrow:'BİRAZ TROPİK, BİRAZ TUTKU',headline:'Ekşisi canlı.|Ruhu tropik.',story:'Passion fruit’in kıpır kıpır ekşiliği, cinin aromatik karakteriyle aynı bardakta.',detail:'Tropik meyvenin yoğun aroması ve cinin bitkisel karakteri. Passion 10, meyvemsi bir başlangıçtan canlı, ekşi bir finale uzanıyor. Her yudumunda başka bir katman.',ingredients:'Cin · Passion fruit',tags:['Ekşi-meyveli','Tropik','Canlı'],image:'/images/passion-10.webp',bg:'#f4e8be',ink:'#634124',profile:[3,4,4,3],visible:true,hero:true},
{id:'tequila-orange-fizz',name:'Tequila Orange Fizz',category:categories[1],eyebrow:'KÖPÜK KÖPÜK FERAHLIK',headline:'Biraz güneş.|Biraz kıpırtı.',story:'Portakalın neşeli aroması, tekilanın karakteri ve yükselen baloncuklar.',detail:'Taze narenciye, ferah bir içim ve hafifçe yükselen baloncuklar. Tequila Orange Fizz, tekilanın karakterini portakalın aydınlık tarafıyla buluşturuyor. Uzun sohbetlere eşlik eden canlı bir lezzet.',ingredients:'Tekila · Portakal · Soda',tags:['Ferah','Gazlı','Portakallı'],image:'/images/tequila-orange-fizz.webp',bg:'#f5e3c4',ink:'#98502a',profile:[3,3,3,2],visible:true,hero:true},
{id:'whiskey-sour',name:'Whiskey Sour',category:categories[2],eyebrow:'KLASİĞİN HAKKINI VEREN',headline:'Denge dediğin|tam da bu.',story:'Viskinin sıcak karakteriyle narenciyenin canlı ekşiliği. Zamansız bir buluşma.',detail:'Güçlü bir karakter, pürüzsüz bir denge. Viskinin sıcak tonları limonun canlılığıyla yumuşuyor. Klasik Whiskey Sour, tanıdık bir lezzete her seferinde yeniden dönmek için iyi bir neden.',ingredients:'Viski · Limon · Şeker',tags:['Ekşi-tatlı','Dengeli','Klasik'],image:'/images/whiskey-sour.webp',bg:'#ece1cc',ink:'#725032',profile:[3,4,3,4],visible:true,hero:true},
{id:'gin-sour',name:'Gin Sour',category:categories[2],eyebrow:'FERAH BİR SAYFA AÇ',headline:'Yeşil bir nefes.|Canlı bir dokunuş.',story:'Cinin bitkisel notaları, narenciyenin tazeliğiyle hafif ve canlı bir ritim yakalıyor.',detail:'Tazeliği sevenlere. Cin, bitkisel ve aromatik notalarını narenciyenin canlı ekşiliğine bırakıyor. Temiz bir başlangıç, dengeli bir gövde ve ferah bir bitiş.',ingredients:'Cin · Narenciye',tags:['Bitkisel','Ferah','Ekşi'],image:'/images/gin-sour.webp',bg:'#e9ecda',ink:'#435239',profile:[2,4,5,3],visible:true,hero:true},
{id:'margarita',name:'Margarita',category:categories[2],eyebrow:'İKONİK OLMANIN BİR SEBEBİ VAR',headline:'Az söz.|Bol karakter.',story:'Lime’ın keskin tazeliği ve tekilanın kendine has duruşu. Klasik, her zaman.',detail:'Lime, tekila ve narenciyenin zamansız uyumu. Margarita’nın çekiciliği yalınlığında: taze, net ve enerjik. Bildiğin, sevdiğin, yeniden buluşmak istediğin bir klasik.',ingredients:'Tekila · Portakal likörü · Lime',tags:['Lime','Klasik','Canlı'],image:'/images/margarita.webp',bg:'#eff0df',ink:'#597045',profile:[2,5,3,4],visible:true,hero:true},
{id:'old-fashioned',name:'Old Fashioned',category:categories[3],eyebrow:'ZAMANA MEYDAN OKUYAN',headline:'Yavaş içilir.|Uzun hatırlanır.',story:'Viskinin başrolde olduğu, sade ama derin bir klasik. Kendinden emin ve güçlü.',detail:'Sözü viskiye bırakan bir klasik. Bitterin ince dokunuşu ve portakalın aroması, güçlü gövdenin etrafında sessizce açılıyor. Old Fashioned, aceleye gelmeyen anların karakterli eşlikçisi.',ingredients:'Viski · Bitter · Şeker · Portakal kabuğu',tags:['Güçlü','Viski odaklı','Klasik'],image:'/images/old-fashioned.webp',bg:'#211919',ink:'#f0debd',profile:[2,1,4,5],visible:true,hero:true},
{id:'gece-kahvesi',name:'Gece Kahvesi',category:categories[4],eyebrow:'GECENİN EN KOYU KARAKTERİ',headline:'Bir fincan.|Kırk yıllık bir gece.',story:'Kahvenin koyu aroması, Türk kahvesi fincanının tanıdık sıcaklığında. Gecenin son sözü.',detail:'Gelenekten bir iz, geceden bir parça. Kahvenin kavruk ve yoğun aroması, Türk kahvesi sunumunun tanıdık ritüeliyle buluşuyor. Güçlü profili ve uzun bitişiyle, sohbetin ağır ağır derinleştiği anlar için.',ingredients:'Kahve aroması',tags:['Kahveli','Yoğun','Güçlü'],image:'/images/gece-kahvesi.webp',bg:'#211818',ink:'#f0dfc0',profile:[2,1,5,5],visible:true,hero:true}
];
