'use client';
import {useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import {ArrowDown,ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play,ArrowUp,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {categories,initialMenu,type Cocktail} from './menu-data';
const num=(n:number)=>String(n).padStart(2,'0');
function Profile({item}:{item:Cocktail}){return <div className="profile">{['Tatlılık','Ekşilik','Aroma','Yoğunluk'].map((label,i)=><div className="profile-row" key={label}><span>{label}</span><div role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={5} aria-valuenow={item.profile[i]}>{[1,2,3,4,5].map(x=><b key={x} className={x<=item.profile[i]?'filled':''}/>)}</div></div>)}</div>}
function Tags({item}:{item:Cocktail}){return <div className="tags">{item.tags.map(t=><span className="pill" key={t}>{t}</span>)}</div>}
export default function Showcase({initialItems}:{initialItems:Cocktail[]}){
 const [menu,setMenu]=useState(initialItems),[active,setActive]=useState(0),[loading,setLoading]=useState(true),[paused,setPaused]=useState(false),[hovered,setHovered]=useState(false),[reduced,setReduced]=useState(false),[selected,setSelected]=useState<Cocktail|null>(null);
 const page=useRef<HTMLDivElement>(null),hero=useRef<HTMLElement>(null),touchX=useRef(0);
 const visible=menu.filter(x=>x.visible),slides=visible.filter(x=>x.hero),item=slides[active%Math.max(1,slides.length)];
 const signature=visible.find(x=>x.id==='orange-silk'),tea=visible.find(x=>x.id==='bodrum-cayi'),peach=visible.find(x=>x.id==='peachy-10'),coffee=visible.find(x=>x.id==='gece-kahvesi');
 const change=(n:number)=>setActive(v=>(v+n+slides.length)%Math.max(1,slides.length));
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');setReduced(q.matches);const sync=()=>setReduced(q.matches);q.addEventListener('change',sync);const timer=setTimeout(()=>setLoading(false),q.matches?150:2100);return()=>{clearTimeout(timer);q.removeEventListener('change',sync)}},[]);
 useEffect(()=>{if(paused||reduced||hovered||loading||slides.length<2)return;const t=setInterval(()=>{if(!document.hidden)setActive(x=>(x+1)%slides.length)},9000);return()=>clearInterval(t)},[paused,reduced,hovered,loading,slides.length]);
 useEffect(()=>{if(loading||reduced)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.12});page.current?.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[loading,reduced,menu]);
 useEffect(()=>{if(reduced||paused)return;let frame=0;const onScroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{page.current?.style.setProperty('--scroll',String(window.scrollY));const h=hero.current;if(h&&window.scrollY<innerHeight*1.3)h.style.setProperty('--parallax',`${window.scrollY*.15}px`);frame=0})};addEventListener('scroll',onScroll,{passive:true});return()=>{removeEventListener('scroll',onScroll);cancelAnimationFrame(frame)}},[reduced,paused]);
 const noMotion=paused||reduced;
 return <div ref={page} className={`showcase ${noMotion?'motion-paused':'motion-on'}`}>
 {loading&&<div className="intro" aria-label="Talha Korkmaz kokteyl seçkisi açılıyor"><span className="small">İYİ İÇKİ. GÜZEL SOHBET.</span><div className="intro-name" aria-label="TALHA KORKMAZ">{'TALHA KORKMAZ'.split('').map((c,i)=><span key={i} style={{animationDelay:`${i*65}ms`}} aria-hidden="true">{c===' '?'\u00a0':c}</span>)}</div><span className="intro-line"/><button onClick={()=>setLoading(false)}>Keşfetmeye başla <ArrowUpRight size={15}/></button></div>}
 <main>
 {item?<section ref={hero} className={`hero hero-${item.id}`} style={{'--slide-bg':item.bg,'--slide-ink':item.ink} as CSSProperties} aria-roledescription="slayt gösterisi" aria-label="Kokteyl sahnesi" onMouseEnter={()=>setHovered(true)} onMouseLeave={()=>setHovered(false)} onFocusCapture={()=>setHovered(true)} onBlurCapture={()=>setHovered(false)} onTouchStart={e=>{touchX.current=e.touches[0].clientX}} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-touchX.current;if(Math.abs(dx)>65)change(dx>0?-1:1)}} onKeyDown={e=>{if(e.key==='ArrowRight')change(1);if(e.key==='ArrowLeft')change(-1)}}>
 <div className="hero-top"><span>BİR KOKTEYLDEN DAHA FAZLASI.</span><span>EV BARI SEÇKİSİ · {num(visible.length)} KARAKTER</span></div>
 <div className="hero-scene" key={item.id}><p className="hero-eyebrow">{item.eyebrow}</p><h1 className={item.name.length>17?'long-title':''}>{(['bodrum-cayi','gece-kahvesi'].includes(item.id)?item.name.toLocaleUpperCase('tr-TR'):item.name.toUpperCase())}</h1><div className="hero-orbit" aria-hidden="true"/><div className="hero-photo"><img src={item.image} alt={item.name} fetchPriority="high" width={1280} height={1280}/></div><div className="hero-story"><span className="small">{num(active%slides.length+1)} / {item.category.toLocaleUpperCase('tr-TR')}</span><h2>{item.headline.split('|')[0]}<br/><i>{item.headline.split('|')[1]}</i></h2><p>{item.story}</p><button className="text-link" onClick={()=>setSelected(item)}>Hikâyesini keşfet <ArrowUpRight size={21}/></button></div><div className="hero-notes"><span className="small">KARAKTERİ</span><p>{item.tags.map(t=><span key={t}>{t}.<br/></span>)}</p><span className="hero-script">iyi ki tanıştık.</span></div></div>
 <div className="hero-bottom"><a href={signature?"#signature":"#collection"} className="scroll-link"><span className="round"><ArrowDown size={17}/></span> AŞAĞIDA DAHA FAZLASI VAR</a><div className="slide-dots" aria-label="Kokteyl seçimi">{slides.map((s,i)=><button key={s.id} onClick={()=>setActive(i)} aria-label={`${s.name} göster`} aria-pressed={active%slides.length===i}><span/></button>)}</div><div className="slide-controls"><span>{num(active%slides.length+1)} <em>/ {num(slides.length)}</em></span><button onClick={()=>change(-1)} aria-label="Önceki kokteyl"><ChevronLeft/></button><button onClick={()=>change(1)} aria-label="Sonraki kokteyl"><ChevronRight/></button></div></div>
 </section>:<section className="empty-menu"><h1>{visible.length?"Her yudumun bir karakteri var.":"Yeni bir hikâye hazırlanıyor."}</h1>{visible.length?<a className="text-link" href="#collection">Kokteylleri keşfet <ArrowDown size={20}/></a>:<p>Seçkimiz yakında burada.</p>}</section>}
 <div className="marquee" aria-hidden="true"><div>{[0,1,2,3].map(n=><span key={n}>İYİ İÇKİ <b>✳</b> GÜZEL SOHBET <b>✳</b> HER YUDUMDA BİR HİKÂYE <b>✳</b></span>)}</div></div>
 {signature&&<section id="signature" className="signature"><div className="section-kicker"><span>01 — SEÇKİNİN İMZASI</span><span>{signature.name.toUpperCase()}</span></div><div className="signature-grid"><div className="signature-title" data-reveal><span className="small">TALHA’NIN İMZASI</span><h2>Bir yudum.<br/><i>Bin küçük <br/>detay.</i></h2><span className="signature-note">Turunçgillerin zarafeti.</span></div><div className="signature-visual" data-reveal><div className="signature-halo"/><img src={signature.image} alt={signature.name} loading="lazy" width={1280} height={1280}/><div className="seal" aria-hidden="true">✳<span>İPEKSİ<br/>BİR İMZA</span></div></div><div className="signature-copy" data-reveal><h3>{signature.name}</h3><p>{signature.detail}</p><Profile item={signature}/><p className="ingredients">{signature.ingredients}</p></div></div><div className="signature-footer"><span>NARENCİYENİN PARLAKLIĞI</span><span>BADEMİN YUMUŞAKLIĞI</span><span>İPEKSİ BİR BİTİŞ</span></div></section>}
 <section className="collection" id="collection"><div className="section-kicker"><span>02 — KOKTEYL SEÇKİSİ</span><span>{num(visible.length)} FARKLI KARAKTER</span></div><div className="collection-heading" data-reveal><h2>Senin <i>karakterin</i><br/>hangisi?</h2><p>Kimi tatlı bir başlangıç.<br/>Kimi güçlü bir son söz.<br/>Hepsinin anlatacak bir hikâyesi var.</p></div>
 {categories.map((category,gi)=>{const items=visible.filter(x=>x.category===category);if(!items.length)return null;return <div className="menu-group" key={category}><div className="group-heading" data-reveal><span>{num(gi+1)}</span><h3>{category}</h3><span className="group-count">{items.length} KOKTEYL</span></div><div className="cocktail-grid">{items.map((c,i)=><button className={`cocktail-card card-${c.id}`} key={c.id} onClick={()=>setSelected(c)} data-reveal style={{'--card-tint':c.bg,'--delay':`${i*80}ms`} as CSSProperties} aria-label={`${c.name} hikâyesini ve lezzet profilini aç`}><div className="card-image"><span className="card-num">{num(visible.indexOf(c)+1)}</span><img src={c.image} alt={c.name} width={1280} height={1280} loading="lazy"/><span className="card-open"><ArrowUpRight size={22}/></span></div><div className="card-caption"><h4>{c.name}</h4><span>{c.tags.join(' · ')}</span></div></button>)}</div></div>})}
 </section>
 {(tea||peach)&&<section className="unexpected" id="unexpected"><div className="section-kicker"><span>03 — BARDAĞIN DIŞINDA DÜŞÜN</span><span>BEKLENMEDİK KARŞILAŞMALAR</span></div><h2 data-reveal>Biraz şaşırtalım.<br/><i>Çokça gülümsetelim.</i></h2><div className="fun-grid">{tea&&<article className="tea-panel" data-reveal><div className="fun-top"><span className="small">EGE’DEN BİR SELAM</span><span className="fun-number">01</span></div><h3>The <i>Çay.</i></h3><div className="fun-visual"><span className="fun-handwritten">Bildiğin çaydan<br/>biraz farklı.</span><img src={tea.image} alt={tea.name} loading="lazy" width={1280} height={1280}/></div><div className="fun-copy"><h4>{tea.name}</h4><p>{tea.story}</p><button className="text-link" onClick={()=>setSelected(tea)}>Tanışalım <ArrowUpRight size={21}/></button></div></article>}{peach&&<article className="peach-panel" data-reveal><div className="fun-top"><span className="small">KEYİF SEVİYESİ: ON ÜZERİNDEN ON</span><span className="fun-number">02</span></div><h3>{peach.name.split(' ')[0]} <i>10.</i></h3><div className="fun-visual"><span className="bubble bubble-one"/><span className="bubble bubble-two"/><span className="bubble bubble-three"/><img src={peach.image} alt={peach.name} loading="lazy" width={1280} height={1280}/><span className="fun-handwritten">Köpükler bizden,<br/>keyfi senden.</span></div><div className="fun-copy"><h4>Küçük küvet. Büyük keyif.</h4><p>{peach.story}</p><button className="text-link" onClick={()=>setSelected(peach)}>Yaza dal <ArrowUpRight size={21}/></button></div></article>}</div></section>}
 {coffee&&<section className="night" id="night"><div className="night-rug"/><div className="section-kicker"><span>04 — GECENİN SON SÖZÜ</span><span>KOYU · YOĞUN · KARAKTERLİ</span></div><div className="night-layout"><div className="night-copy" data-reveal><span className="small">TANIDIK BİR RİTÜEL. BAŞKA BİR GECE.</span><h2>{coffee.name.split(' ')[0]}<br/><i>{coffee.name.split(' ').slice(1).join(' ')}.</i></h2><p>{coffee.detail}</p><Tags item={coffee}/><button className="text-link" onClick={()=>setSelected(coffee)}>Gecenin karakterini keşfet <ArrowUpRight size={22}/></button></div><div className="night-image" data-reveal><span className="night-phrase">Hatırı uzun.<br/>Karakteri koyu.</span><img src={coffee.image} alt={coffee.name+' — Türk kahvesi fincanı ve bakır cezve sunumu'} loading="lazy" width={1280} height={1280}/></div></div><div className="night-bottom"><span>GELENEKTEN BİR İZ</span><span>GECEDEN BİR PARÇA</span></div></section>}
 <section className="closing"><div className="closing-line" data-reveal><span className="small">BARDAKLAR BOŞALIR. HİKÂYELER KALIR.</span><h2>Güzel içkiler,<br/><i>güzel insanları</i><br/>bir araya getirir.</h2><span className="closing-star" aria-hidden="true">✳</span></div><div className="designer" data-reveal><div className="portrait"><img src="/images/talha-bar-portrait.webp" alt="Talha Korkmaz, bar ortamında hazırlanmış yaratıcı portre" loading="lazy" width={1086} height={1448}/></div><div><span className="small">SEÇKİ & TASARIM</span><h3>Talha Korkmaz</h3><p>Biraz merak, biraz yaratıcılık.<br/>Ve paylaşmaya değer tatlar.</p><span className="signature-name">Talha.</span></div></div></section>
 </main><footer><span>© {new Date().getFullYear()} TALHA KORKMAZ</span><span>İYİ İÇKİ. GÜZEL SOHBET. DAİMA.</span><a href="#" aria-label="Sayfanın başına dön">BAŞA DÖN <ArrowUp size={15}/></a></footer><button className="motion-toggle" onClick={()=>setPaused(p=>!p)} aria-label={noMotion?'Animasyonları başlat':'Animasyonları durdur'} title={noMotion?'Hareketi başlat':'Hareketi durdur'}>{noMotion?<Play size={13}/>:<Pause size={13}/>}<span>{noMotion?'Hareket kapalı':'Hareket açık'}</span></button>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="drink-dialog" showCloseButton={false}>{selected&&<><DialogClose className="dialog-close" aria-label="Kapat"><X size={24}/></DialogClose><div className="dialog-visual" style={{background:selected.bg}}><img src={selected.image} alt={selected.name} width={1280} height={1280}/></div><div className="dialog-copy"><span className="small">{selected.category.toLocaleUpperCase('tr-TR')}</span><DialogTitle className="dialog-name">{selected.name}</DialogTitle><Tags item={selected}/><DialogDescription className="dialog-story">{selected.detail}</DialogDescription><h3 className="small">LEZZET HARİTASI</h3><Profile item={selected}/><p className="ingredients">{selected.ingredients}</p></div></>}</DialogContent></Dialog>
 </div>
}
