import {initialMenu,categories} from '../../menu-data';
import {isEditor,validOrigin} from '../../admin-auth';
import {getChatGPTUser} from '../../chatgpt-auth';
import {database} from '../../../db/storage';
import {z} from 'zod';
const item=z.object({id:z.string().regex(/^[a-z0-9-]{1,80}$/),name:z.string().trim().min(1).max(60),category:z.enum(categories),eyebrow:z.string().max(100),headline:z.string().max(120),story:z.string().max(500),detail:z.string().max(1800),ingredients:z.string().max(500),tags:z.array(z.string().min(1).max(35)).min(1).max(5),image:z.string().regex(/^\/(?:images\/[a-zA-Z0-9._-]+|api\/images\/[a-zA-Z0-9._-]+)$/),bg:z.string().regex(/^#[0-9a-fA-F]{6}$/),ink:z.string().regex(/^#[0-9a-fA-F]{6}$/),profile:z.tuple([z.number().int().min(0).max(5),z.number().int().min(0).max(5),z.number().int().min(0).max(5),z.number().int().min(0).max(5)]),visible:z.boolean(),hero:z.boolean()});
const body=z.object({items:z.array(item).max(100),revision:z.number().int().min(0)}).refine(d=>new Set(d.items.map(x=>x.id)).size===d.items.length,'Ürün kimlikleri benzersiz olmalı.');
export async function GET(){try{const row=await database().prepare('SELECT body,revision FROM menu_document WHERE id=?').bind('cocktails').first<{body:string;revision:number}>();return Response.json({items:row?JSON.parse(row.body):initialMenu,revision:row?.revision??0},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error('Menu read unavailable',e);return Response.json({error:'Seçki şu anda yüklenemiyor.'},{status:503})}}
export async function PUT(request:Request){if(!await isEditor())return Response.json({error:'Bu işlem için düzenleme yetkisi gerekiyor.'},{status:403});if(!validOrigin(request))return Response.json({error:'Geçersiz istek kaynağı.'},{status:403});if(Number(request.headers.get('content-length')||0)>400000)return Response.json({error:'İçerik çok büyük.'},{status:413});try{const raw=await request.text();if(raw.length>400000)return Response.json({error:'İçerik çok büyük.'},{status:413});const parsed=body.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Lütfen alanları kontrol et. Ürün adı, görsel ve lezzet değerleri geçerli olmalı.'},{status:400});const {items,revision}=parsed.data;const user=await getChatGPTUser();const db=database();const result=revision===0?await db.prepare('INSERT INTO menu_document (id,body,revision,updated_by,updated_at) VALUES (?,?,1,?,?) ON CONFLICT(id) DO NOTHING').bind('cocktails',JSON.stringify(items),user!.userId,new Date().toISOString()).run():await db.prepare('UPDATE menu_document SET body=?,revision=revision+1,updated_by=?,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(items),user!.userId,new Date().toISOString(),'cocktails',revision).run();if(!result.meta.changes)return Response.json({error:'Seçki başka bir pencerede değiştirildi. Taslağını indirip sayfayı yenile.'},{status:409});return Response.json({revision:revision+1})}catch(e){console.error('Menu save failed',e);return Response.json({error:'Kaydedilemedi. Değişikliklerin bu ekranda duruyor; yeniden deneyebilirsin.'},{status:503})}}
